on: 
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]
name: Build
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Show the env
        id: show
        env:
          QEMU_LD_PREFIX: /usr/arm-linux-gnueabihf
        run: |
          sudo apt update && sudo apt-get install -y gcc-arm-linux-gnueabihf
          ls /usr | grep arm
      - name: Build and Push
        uses: docker/build-push-action@v2
        id: build
        env:
          QEMU_LD_PREFIX: /usr/arm-linux-gnueabihf
        with:
          context: .
          platforms: linux/arm/v7
          build-args: |
            QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
          push: true
          tags: ziporah/fabio:latest 
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker image inspect ${{ steps.build.outputs.digest }}
